fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: App\Entity\User
    service:
        mailer: fos_user.mailer.twig_swift

    from_email:
          address:        gilbert.simonj@gmail.com
          sender_name:    ClimaClass
    resetting:
         email:
             template:   '@FOSUser/Resetting/email.txt.twig'
         form:
             type:               FOS\UserBundle\Form\Type\ResettingFormType # or 'fos_user_resetting' on Symfony < 2.8
             name:               fos_user_resetting_form
             validation_groups:  [ResetPassword, Default]
    registration:
         confirmation:
             enabled: true
             template:   '@FOSUser/Registration/email.txt.twig'
    profile:
      form:
        type: App\Form\ProfileForm
