#index:
#    path: /
#    controller: App\Controller\DefaultController::index
fos_user_security:
  resource: "@FOSUserBundle/Resources/config/routing/security.xml"
easy_admin_bundle:
  resource: '@EasyAdminBundle/Controller/EasyAdminController.php'
  prefix: /admin
  type: annotation

publication:
  path: /publication/
  controller: App\Controller\PublicationController
messages_form:
  path: /teacher/messages/{receiver}
  controller: App\Controller\UserController::sendMessage
class_message:
  path: /teacher/class/{classReceiver}
  controller: App\Controller\ClassRoomController::sendMessage
classroom_messages:
  path: classroom_messages/{classroom_id}
  controller: App\Controller\ClassRoomController::seeAllMessages
mymessages:
  path: /mymessages/
  controller: App\Controller\ClassRoomController::myMessages
classroom_conversation:
  path: classroom/{classroom_contact_a}/{classroom_contact_b}
  controller: App\Controller\ClassRoomController::seeMessages
classroom_profil:
  path: /classroom_profil/{id}
  controller: App\Controller\ClassroomController::classroom
new_publication:
  path: /teacher/new_publication
  controller: App\Controller\TeacherController::add_publication