#index:
#    path: /
#    controller: App\Controller\DefaultController::index
fos_user_security:
  resource: "@FOSUserBundle/Resources/config/routing/security.xml"
easy_admin_bundle:
  resource: '@EasyAdminBundle/Controller/EasyAdminController.php'
  prefix: /admin
  type: annotation
myclass:
  path: /myclass
  controller: App\Controller\MyClassController
classroom:
  path: /classroom/{id}
  controller: App\Controller\ClassRoomController
