#index:
#    path: /
#    controller: App\Controller\DefaultController::index
fos_user_security:
  resource: "@FOSUserBundle/Resources/config/routing/security.xml"
easy_admin_bundle:
  resource: '@EasyAdminBundle/Controller/EasyAdminController.php'
  prefix: /admin
  type: annotation

classroom:
  path: /classroom/{id}
  controller: App\Controller\ClassRoomController
publication:
  path: /publication/
  controller: App\Controller\PublicationController
messages_form:
  path: /teacher/messages/{receiver}
  controller: App\Controller\UserController::sendMessage
class_message:
  path: /teacher/class/{classReceiver}
  controller: App\Controller\ClassRoomController::sendMessage
classroom_messages:
  path: classroom_messages/{classroom_id}
  controller: App\Controller\ClassRoomController::seeAllMessages
